//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Proekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class podatoci2
    {
        public string datum { get; set; }
        public string vreme { get; set; }
        public string temperatura { get; set; }
    }
}
